eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8801
spring:
  application:
    name: shop-edit
  #（1）数据源
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/pinyougoudb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123
      #初始化时建立物理连接的个数
      initial-size: 10
      #最大连接池数量
      max-active: 20
      #Oracle打开。mysql关闭
      pool-prepared-statements: false
      #判断是不是查询语句
      validation-query: SELECT 1
      #查询超时时间
      validation-query-timeout: 500
      #开启防火墙、监控、日志插件
      filters: stat,wall
      #开启监控
      stat-view-servlet:
        enabled: true
        #访问地址规则
        url-pattern: /druid/*
        #登录用户名
        login-username: admin
        #登录密码
        login-password: admin
        #是否允许清空统计数据
        reset-enable: true
      #其他检测功能不开，损耗性能
      test-on-borrow: false
      test-on-return: false
      #开启查询验证超时检测
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
---
spring:
  redis:
    # Redis默认库
    database: 0
    host: localhost
    port: 6379
    password: 123
    #默认为0，最好修改到200以上
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
#分页
pagehelper:
  helperDialect: mysql
  reasonable: true

mybatis:
  mapper-locations: classpath:/com.shop.mapper/*.xml