server:
  port: 8888   # 端口号
spring:
  application:
    name: zuul-com.shop  # 网关服务名称
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka     #eureka注册中心地址
zuul:
  routes:
    api-a:
      path: /auth/**
      service-id: Auth-server
    api-b:
      path: /order/**
      service-id: resource-server
    api-c:
      path: /order/shop-query/**
      service-id: shop-query
    api-d:
      path: /order/shop-edit/**
      service-id: shop-edit